### ISSUE TITLE
Mavericks compatibility

### ISSUE THREAD

**Issue by ufgh** [wshanks/applescripts#1]
`AppleScript/PowerSave.applescript` is no longer fully functional in Mavericks. For example, brightness is no longer set, because `click menu item "Displays" of menu "View" of menu bar 1` fails. In addition, the "Enable access for assistive devices" feature in OS X 10.9 is significantly modified, so much so that it's in a different preference pane. I'm sure there are other issues as well.

**Comment by wshanks** [comment]
Thanks for the notification.  I'm pretty conservative about operating system upgrades, so I probably won't be able to address this too quickly (I at least want to wait until there are fewer open issues with 10.9 in the title at https://github.com/mxcl/homebrew/issues).  I will definitely fix this once I have access to a machine running 10.9 though.  I'd also accept a pull request in the mean time if someone else fixed it first.

Actually, this is the first time I've ever heard from someone else using my applescripts.  I hope they are useful.
